spring.application.name=JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/animal-crossing
spring.datasource.username=postgres
spring.datasource.password=Nf101308!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=1010